module.exports = {
    'TOKEN_STRING': 1,
    'TOKEN_NUMBER': 2,
    'TOKEN_OPENING_BRACE': 3,
    'TOKEN_CLOSING_BRACE': 4,
    'TOKEN_OPENING_BRACKET': 5,
    'TOKEN_CLOSING_BRACKET': 6,
    'TOKEN_TRUE': 7,
    'TOKEN_FALSE': 8,
    'TOKEN_NULL': 9,
    'TOKEN_EOF': 10,
    'TOKEN_COLON': 11
};